# Generated by Django 5.1 on 2024-08-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_location_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
